# Generated by Django 4.0.6 on 2022-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название точки')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
            },
        ),
    ]
