# Generated by Django 4.1 on 2022-08-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="tg_chat_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Id чата для telegram"
            ),
        ),
    ]
