# Generated by Django 4.1 on 2022-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_alter_participant_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="tg_chat_id",
            field=models.IntegerField(unique=True, verbose_name="Id чата для telegram"),
        ),
    ]
