# Generated by Django 4.1 on 2022-08-14 20:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationTexts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_message",
                    ckeditor.fields.RichTextField(
                        help_text="Отправляем при первом входе в бота",
                        verbose_name="Welcome message",
                    ),
                ),
                (
                    "race_disclaimer",
                    ckeditor.fields.RichTextField(
                        help_text="Можно указать примерную инфу о механике гонки/соглашение, что никто не несет ответсвенность",
                        verbose_name="Дисклеймер перед регистрацией",
                    ),
                ),
                (
                    "after_reg_message",
                    ckeditor.fields.RichTextField(
                        help_text="Можно указать информацию о месте и времени сбора",
                        verbose_name="Сообщение после регистрации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текст для регистрации в боте",
                "verbose_name_plural": "Тексты для регистрации в боте",
            },
        ),
    ]
