# Generated by Django 4.1 on 2022-08-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_settings", "0002_alter_registrationtexts_after_reg_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_message",
                    models.TextField(
                        help_text="Отправляем для старта гонки",
                        verbose_name="Сообщение о старте",
                    ),
                ),
                (
                    "winner_message",
                    models.TextField(
                        help_text="Отправляем выбранным участникам",
                        verbose_name="Сообщение для победителей",
                    ),
                ),
                (
                    "custom_message",
                    models.TextField(
                        blank=True,
                        help_text="Отправляем всем участникам",
                        verbose_name="Кастомное сообщение для всех",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текст для гонки",
                "verbose_name_plural": "Тексты для гонки",
            },
        ),
    ]
