# Generated by Django 4.1 on 2022-08-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo_points", "0003_geopoints_is_start_or_finish_point_and_more"),
        ("participants", "0005_alter_participant_name"),
        ("race", "0004_remove_racephoto_album_remove_race_photos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="participants.participant",
                to_field="tg_chat_id",
                verbose_name="Участник",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="points",
            field=models.ManyToManyField(
                blank=True,
                to="geo_points.geopoints",
                verbose_name="Точки, которые были финишированы",
            ),
        ),
    ]
