# Generated by Django 4.1 on 2022-08-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0003_alter_participant_tg_chat_id"),
        (
            "geo_points",
            "0002_remove_geopoints_latitude_remove_geopoints_longitude_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_of_start",
                    models.DateTimeField(blank=True, verbose_name="Время старта"),
                ),
                (
                    "time_of_finish",
                    models.DateTimeField(blank=True, verbose_name="Время финиша"),
                ),
                (
                    "place",
                    models.SmallIntegerField(
                        default=0, verbose_name="Место в общем зачёте"
                    ),
                ),
                (
                    "place_in_category",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Место в категории"
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Закончил гонку"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.participant",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гонка",
                "verbose_name_plural": "Гонка",
            },
        ),
        migrations.CreateModel(
            name="RaceAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="race.race"
                    ),
                ),
            ],
            options={
                "verbose_name": "Альбом с фотографиями",
                "verbose_name_plural": "Альбомы с фотографиями",
            },
        ),
        migrations.CreateModel(
            name="RacePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="photos", verbose_name="Фотография"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race.racealbum",
                        verbose_name="Альбом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотография",
            },
        ),
        migrations.AddField(
            model_name="race",
            name="photos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="race.racealbum",
                verbose_name="Фотографии с гонки",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="points",
            field=models.ManyToManyField(
                to="geo_points.geopoints",
                verbose_name="Точки, которые были финишированы",
            ),
        ),
    ]
