# Generated by Django 4.1 on 2022-08-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "geo_points",
            "0002_remove_geopoints_latitude_remove_geopoints_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="geopoints",
            name="is_start_or_finish_point",
            field=models.SmallIntegerField(
                choices=[(0, "Не старт и не финиш"), (1, "Старт"), (2, "Финиш")],
                default=0,
                help_text="Устанавливаем только широту/долготу старта участка",
                null=True,
                verbose_name="Является стартовой или финишной точкой",
            ),
        ),
        migrations.AlterField(
            model_name="geopoints",
            name="latitude_finish",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта финиша участка",
            ),
        ),
        migrations.AlterField(
            model_name="geopoints",
            name="longitude_finish",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота финиша участка",
            ),
        ),
    ]
