# Generated by Django 4.1 on 2022-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationtexts",
            name="after_reg_message",
            field=models.TextField(
                help_text="Можно указать информацию о месте и времени сбора",
                verbose_name="Сообщение после регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="registrationtexts",
            name="race_disclaimer",
            field=models.TextField(
                help_text="Можно указать примерную инфу о механике гонки/соглашение, что никто не несет ответсвенность",
                verbose_name="Дисклеймер перед регистрацией",
            ),
        ),
        migrations.AlterField(
            model_name="registrationtexts",
            name="welcome_message",
            field=models.TextField(
                help_text="Отправляем при первом входе в бота",
                verbose_name="Welcome message",
            ),
        ),
    ]
